/****** Object:  Database [PruebaXamarinBD]    Script Date: 6/8/2020 11:07:21 ******/
CREATE DATABASE [PruebaXamarinBD]  (EDITION = 'Standard', SERVICE_OBJECTIVE = 'S0', MAXSIZE = 1 GB) WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS;
GO

ALTER DATABASE [PruebaXamarinBD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PruebaXamarinBD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PruebaXamarinBD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PruebaXamarinBD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PruebaXamarinBD] SET ARITHABORT OFF 
GO

ALTER DATABASE [PruebaXamarinBD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PruebaXamarinBD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PruebaXamarinBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PruebaXamarinBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PruebaXamarinBD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PruebaXamarinBD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PruebaXamarinBD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PruebaXamarinBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PruebaXamarinBD] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [PruebaXamarinBD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PruebaXamarinBD] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [PruebaXamarinBD] SET  MULTI_USER 
GO

ALTER DATABASE [PruebaXamarinBD] SET ENCRYPTION ON
GO

ALTER DATABASE [PruebaXamarinBD] SET QUERY_STORE = ON
GO

ALTER DATABASE [PruebaXamarinBD] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [PruebaXamarinBD] SET  READ_WRITE 
GO

